---
title: "ITS2 Figure 1"
author: "Courtney Hoskinson"
date: "2025-02-28"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Figure 1
library(microbiome)
library(phyloseq)
library(microbiome)
library(phyloseq)
library(funrar)
library(compositions)
library(DirichletMultinomial)
library(lattice)
library(xtable)
library(parallel)
library(RColorBrewer)
library(dplyr)
library(networkD3)
library(Maaslin2)
library(ComplexHeatmap)


load("~/Mar2.RData")

pseq <- microbiome::transform(ITS2_noUnk_4k_genus, "compositional")
pseq <- aggregate_rare(pseq, level = "Genus", detection = 1/100, 
                       prevalence = 10/100)
ps.stool.df <- psmelt(pseq)
ggplot(ps.stool.df, aes(x = agedays/31, y = Abundance, colour = OTU)) +
  theme_classic()+ xlab("Age (months)") + ylab("Abundance (%)") + 
  geom_smooth(se= TRUE, size=2, linetype = "dashed")+
  scale_y_continuous(expand = c(0, 0)) +scale_x_continuous(expand = c(0, 0)) + 
  theme(axis.title.x=element_text(size=15, colour = 'black'))  +
  theme(
    legend.text = element_text(face = "italic"))+
  theme(axis.title.x=element_text(size=15, colour = 'black')) +
  theme(axis.title.y=element_text(size=15, colour = 'black')) +
  theme(axis.text.x=element_text(size=15, colour = 'black')) +
  theme(axis.text.y=element_text(size=15, colour = 'black'))+ 
  scale_color_manual(values = c( "white", "blue", "dodgerblue",
                                 "#00AFBB", "green", "#117733", 
                                 "#009E73",  "#999933","orange",
                                 "#F0E442", "#D55E00", "red", 
                                 "pink","#CC79A7", "#999999", 
                                 "#000000")) + xlim(3, 18) + facet_wrap(~site)
```
```{r}
#Figure 2
ITS2_noUnk_4k_genus@sam_data$SampleID <- as.factor(rownames(ITS2_noUnk_4k_genus@sam_data))
sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
sampledata2 <- subset(sampledata2, sampledata2$Visit == '1 year')
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITSandSpecies"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest_1y <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest_1y$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest_1y$SampleID)
PredictedAgetest_1y$agedays <- as.numeric(sampledata2test$agedays)

ITS2_noUnk_4k_genus@sam_data$SampleID <- as.factor(rownames(ITS2_noUnk_4k_genus@sam_data))
sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
sampledata2 <- subset(sampledata2, sampledata2$Visit == '3 month')
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITSandSpecies"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest$agedays <- as.numeric(sampledata2test$agedays)

df <- rbind(PredictedAgetest, PredictedAgetest_1y)

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
dat <- data.frame(
  x = df$agedays,
  y = df$PredictedAge
)
df$density <- get_density(dat$x, dat$y, n = 2824)

ggplot(df, aes(x=PredictedAge * 12, y=agedays / 30, color = density)) + 
  geom_point()+ theme_classic() + 
  geom_smooth(method=lm) + xlab("") + 
  ylab("") +scale_color_gradientn(colors = colorRampPalette(c( 'lightblue', 'lightgray', 'pink',"red"))(10000)) +
  theme(axis.title.y=element_text( size=10, colour = 'black')) +
  theme(axis.text.x=element_text(size=10, colour = 'black')) +
  theme(axis.text.y=element_text(size=10, colour = 'black')) +
  theme(axis.title.x=element_text( size=10, colour = 'black')) 
```

```{r}
import <- as.data.frame(PREDAGE[["RB_ITSandSpecies"]][["Importance"]])
import$rf.impt <- as.numeric(import$rf.impt)
import <- as.data.frame(import)
import <- subset(import, rf.impt > 1.412282) # top 25
import$type_bf <- 'Bacteria'
import$type_bf[rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b' | rownames(import) == 'p__Ascomycota_f__Erysiphaceae_g__Blumeria___72091681d37ab25f17ef8cfb3270cc72' | rownames(import) == 'p__Ascomycota_f__Pichiaceae_g__Pichia___9bf97711725cf823c6ca7c15562b6980' | rownames(import) == 'p__Ascomycota_f__Saccharomycetaceae_f__Saccharomycetaceae.unknown___4d97ab3f971eba77e9ac20157009492b' | rownames(import) == 'p__Ascomycota_f__Saccharomycetales_fam_Incertae_sedis_g__Candida___d182ac953a71506c2ee448eb68a77448' | rownames(import) == 'p__Ascomycota_NA.unknown_NA.unknown___4b79a63c290e13054230ad3d5a884aab' | rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b'] <- 'Fungi'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b' ] <- 'g_Malassezia'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Erysiphaceae_g__Blumeria___72091681d37ab25f17ef8cfb3270cc72' ] <- 'g__Blumeria'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Pichiaceae_g__Pichia___9bf97711725cf823c6ca7c15562b6980' ] <- 'g__Pichia'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Saccharomycetaceae_f__Saccharomycetaceae.unknown___4d97ab3f971eba77e9ac20157009492b' ] <- 'f__Saccharomycetaceae unknown'
import$Row.names[rownames(import) == 'p__Ascomycota_NA.unknown_NA.unknown___4b79a63c290e13054230ad3d5a884aab' ] <- 'p__Ascomycota unknown'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b' ] <- 'g__Malassezia'
ggplot(import,
aes(x=rf.impt, y= reorder(Row.names,rf.impt), color = type_bf, fill = type_bf))+
geom_bar(stat="identity") +
theme_bw() +
theme(axis.line = element_line(colour = "black"),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
panel.border = element_blank(),
panel.background = element_blank(),
legend.title=element_text(size=14),
legend.text=element_text(size=14))  +
xlab("Importance") +
ylab(NULL)+                                                    # Change colors in ggplot2 plot
scale_color_manual(values = c( 'coral',"cornflowerblue"))+                                                    # Change colors in ggplot2 plot
scale_fill_manual(values = c( 'coral',"cornflowerblue")) +
theme(axis.title.x=element_text( size=14, colour = 'black')) +
theme(axis.title.y=element_text(size=14, colour = 'black')) +
theme(axis.text.x=element_text( size=16, colour = 'black')) +
theme(axis.text.y=element_text(size=14, colour = 'black')) + xlim(0,31) + theme(axis.text.y=element_text(size=14, colour = 'black', face = 'italic'))
```


```{r}
#Figure 3

ITS2_noUnk_4k_genus@sam_data$SampleID <- as.factor(rownames(ITS2_noUnk_4k_genus@sam_data))
sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
sampledata2 <- subset(sampledata2, sampledata2$Visit == '1 year')
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest_1y <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest_1y$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest_1y$SampleID)
PredictedAgetest_1y$agedays <- as.numeric(sampledata2test$agedays)

ITS2_noUnk_4k_genus@sam_data$SampleID <- as.factor(rownames(ITS2_noUnk_4k_genus@sam_data))
sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
sampledata2 <- subset(sampledata2, sampledata2$Visit == '3 month')
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest$agedays <- as.numeric(sampledata2test$agedays)

df <- rbind(PredictedAgetest, PredictedAgetest_1y)

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
dat <- data.frame(
  x = df$agedays,
  y = df$PredictedAge
)
df$density <- get_density(dat$x, dat$y, n = 2824)

ggplot(df, aes(x=PredictedAge * 12, y=agedays / 30, color = density)) + 
  geom_point()+ theme_classic() + 
  geom_smooth(method=lm) + xlab("") + 
  ylab("") +scale_color_gradientn(colors = colorRampPalette(c( 'blue', 'lightgray',"red"))(10000)) +
  theme(axis.title.y=element_text( size=10, colour = 'black')) +
  theme(axis.text.x=element_text(size=10, colour = 'black')) +
  theme(axis.text.y=element_text(size=10, colour = 'black')) +
  theme(axis.title.x=element_text( size=10, colour = 'black'))
```


```{r}
import <- as.data.frame(PREDAGE[["RB_ITS"]][["Importance"]]) #extract importance ranking from previously generated predicted age.
View(import)
colnames(import) <- c('Importance', 'Genus')
import <- import[order(-import$Importance),]
import <- import[ c(1:25), ]
import$type_bf <- 'Fungi'

import$Row.names[rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b' ] <- 'g_Malassezia'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Erysiphaceae_g__Blumeria___72091681d37ab25f17ef8cfb3270cc72' ] <- 'g__Blumeria'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Pichiaceae_g__Pichia___9bf97711725cf823c6ca7c15562b6980' ] <- 'g__Pichia'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Saccharomycetaceae_f__Saccharomycetaceae.unknown___4d97ab3f971eba77e9ac20157009492b' ] <- 'f__Saccharomycetaceae unknown'
import$Row.names[rownames(import) == 'p__Ascomycota_NA.unknown_NA.unknown___4b79a63c290e13054230ad3d5a884aab' ] <- 'p__Ascomycota unknown'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Malasseziaceae_g__Malassezia___24f2fe1ad183c246024b31ffa76aab9b' ] <- 'g__Malassezia'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Saccharomycetales_fam_Incertae_sedis_g__Candida___d182ac953a71506c2ee448eb68a77448' ] <- 'g__Candida'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Aspergillaceae_g__Penicillium___6ccb3a96162742306a7a01de4e7a343d' ] <- 'g__Penicillium'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Mycenaceae_g__Mycena___8b976907dff8fa97c161c9f75a9495ec' ] <- 'g__Mycena'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Sporidiobolaceae_g__Rhodotorula___facd2a41707f9dd1af63da1e64a0395a' ] <- 'g__Rhodotorula'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Saccharomycetaceae_g__Saccharomyces___3ce4f6865cacfcb0c91dd4b703792e8c' ] <- 'g__Saccharomyces'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Cladosporiaceae_g__Cladosporium___791ceba534cbfdb93828f9cf95d9121b' ] <- 'g__Cladosporium'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Aspergillaceae_g__Aspergillus___c3903eed8eba252c824a65bd565b0fb3' ] <- 'g__Aspergillus'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Pyronemataceae_g__Aleurina___8852a36ad513b0410fa33393f68f366e' ] <- 'g__Aleurina'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Physalacriaceae_g__Strobilurus___ed551f85959064a56b8639c03cfe0ead' ] <- 'g__Strobilurus'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Aspergillaceae_f__Aspergillaceae.unknown___0c758437c3a60f3f61b61eca533292dd' ] <- 'f__Aspergillaceae unknown'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Metschnikowiaceae_g__Clavispora___08eaddb4ae7f1a64afc190961da72f42' ] <- 'g__Clavispora'
import$Row.names[rownames(import) == 'p__Ascomycota_f__Herpotrichiellaceae_g__Exophiala___e718824f1412896e58e51b2ae22739dc' ] <- 'g__Exophiala'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Strophariaceae_g__Hypholoma___0b28870662e84af050267c447f6de102' ] <- 'g__Hypholoma'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Filobasidiaceae_g__Naganishia___1ab1c230b7ae8238b626431b8bc45369' ] <- 'g__Naganishia'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Bulleribasidiaceae_g__Vishniacozyma___9f377ec11f8170e86393c56de0333849' ] <- 'g__Vishniacozyma'
import$Row.names[rownames(import) == 'p__Ascomycota_o__Saccharomycetales.unknown_o__Saccharomycetales.unknown___010aa1722118f8a31bcfdfdcdfc3c572' ] <- 'o__Saccharomycetales unknown'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Omphalotaceae_f__Omphalotaceae.unknown___cc9871a48b847379af3b7c0893b684ca' ] <- 'f__Omphalotaceae unknown'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Atheliaceae_g__Athelia___04c61485f4a258b2a240ce775ce29273' ] <- 'g__Athelia'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Tricholomataceae_f__Tricholomataceae.unknown___efbb79992a377b337e943c5d4cf414a8' ] <- 'f__Tricholomataceae unknown'
import$Row.names[rownames(import) == 'p__Basidiomycota_f__Hygrophoropsidaceae_g__Hygrophoropsis___52a5b7e75df204165fb0f62ed379c718' ] <- 'g__Hygrophoropsis'

ggplot(import,
aes(x=Importance, y= reorder(Row.names,Importance),fill=type_bf, color=type_bf))+
geom_bar(stat="identity") +
theme_bw() +
theme(axis.line = element_line(colour = "black"),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
panel.border = element_blank(),
panel.background = element_blank(),
legend.title=element_text(size=14),
legend.text=element_text(size=14))  +
xlab("Importance") +
ylab(NULL)+                                                    # Change colors in ggplot2 plot
scale_color_manual(values = c( "cornflowerblue"))+                                                    # Change colors in ggplot2 plot
scale_fill_manual(values = c( "cornflowerblue")) +
theme(axis.title.x=element_text( size=14, colour = 'black')) +
theme(axis.title.y=element_text(size=14, colour = 'black')) +
theme(axis.text.x=element_text( size=16, colour = 'black')) +
theme(axis.text.y=element_text(size=14, colour = 'black')) + xlim(0,80) + theme(axis.text.y=element_text(size=14, colour = 'black', face = 'italic'))
```


```{r}
set.seed(1)
sampledata2 <- as.data.frame(ME_3mo_species_pruned@sam_data)
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$at_least_1_focus_5year_annotated, data=PredictedAgetest)
#W = 29171, p-value = 0.246
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_1_focus_5year_annotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAge$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
at_least_1_focus_5year_annotated_age <- PredictedAgetest$PredictedAge
at_least_1_focus_5year_annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_2_5Y != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$at_least_2_5Y, data=PredictedAgetest)
#W = 21565, p-value = 0.09694
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_2_5Y == "1")
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
at_least_2_5Y_age <- PredictedAgetest$PredictedAge
at_least_2_5Y_age_5year_annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$ad5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$ad5yannotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$ad5yannotated, data=PredictedAgetest)
#W = 19452, p-value = 0.2722
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$ad5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
ad5yannotated_age <- PredictedAgetest$PredictedAge
ad5yannotated_age_chronological <- sampledata2test$exact_age


PredictedAge <- as.data.frame(PREDAGE[["RB_Species"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$asthma5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$asthma5yannotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$asthma5yannotated, data=PredictedAgetest)
#W = 19452, p-value = 0.9804
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$asthma5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
asthma5yannotated_age <- PredictedAgetest$PredictedAge
asthma5yannotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$fa5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$fa5yannotated != '0')
PredictedAgetest1 <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest1$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest1$SampleID)
PredictedAgetest1 <- PredictedAgetest1[reorder_idx, ]
wilcox.test(PredictedAgetest1$PredictedAge~sampledata2test$fa5yannotated, data=PredictedAgetest1)
#W = 5957, p-value = 0.09631
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$fa5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
fa5yannotated_age <- PredictedAgetest$PredictedAge
fa5yannotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$chcla5yq42annotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$chcla5yq42annotated, data=PredictedAgetest)
#W = 9229, p-value = 0.8497
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
chcla5yq42annotated_age <- PredictedAgetest$PredictedAge
chcla5yq42annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated == 'Healthy')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
healthy_age <- PredictedAgetest$PredictedAge
healthy_age_chronological <- sampledata2test$exact_age

mean(chcla5yq42annotated_age) #0.4441469
mean(fa5yannotated_age) #0.3947167
mean(asthma5yannotated_age) #0.4250603
mean(ad5yannotated_age) #0.4190724
mean(at_least_2_5Y_age) #0.4323092
mean(at_least_1_focus_5year_annotated_age) #0.4255688
mean(healthy_age) #0.4366365

ggplot()  + theme_classic() + 
  geom_boxplot(aes(x="Atopic dermatitis", y=(ad5yannotated_age * 12)/(ad5yannotated_age_chronological*12), fill = "Atopic dermatitis")) + 
  geom_boxplot(aes(x= "Asthma", y=(asthma5yannotated_age* 12)/(asthma5yannotated_age_chronological*12), fill = "Asthma"))+ 
  geom_boxplot(aes(x="Food allergy", y=(fa5yannotated_age* 12)/(fa5yannotated_age_chronological*12), fill = "Food allergy")) + 
  geom_boxplot(aes(x= "Allergic rhinitis", y=(chcla5yq42annotated_age* 12)/(chcla5yq42annotated_age_chronological*12), fill = "Allergic rhinitis"))+ 
  geom_boxplot(aes(x= "No diagnoses", y=(healthy_age* 12)/(healthy_age_chronological*12), fill = "No diagnoses"))+ 
  geom_boxplot(aes(x="One or more diagnoses", y=(at_least_2_5Y_age* 12)/(at_least_2_5Y_age_5year_annotated_age_chronological*12), fill = "One or more diagnoses")) + 
  geom_boxplot(aes(x= "Two or more diagnoses", y=(at_least_1_focus_5year_annotated_age*12)/(at_least_1_focus_5year_annotated_age_chronological*12), fill = "Two or more diagnoses")) +
  theme(axis.title.x=element_text(size=14, colour = 'black')) +
  theme(axis.title.y=element_text(size=14, colour = 'black')) +
  theme(axis.text.x=element_text(size=14, colour = 'black', angle = 70, hjust = 1)) +
  theme(axis.text.y=element_text(size=14, colour = 'black')) +
  ggtitle("") + 
  ylab("Fungal-derived/chronological age (months)") + 
  xlab("")+
  scale_fill_manual(values = c(
    "#ddcc77" ,   "lavender" ,  "#AA4499" ,   "#117733"   , "#88CCEE" ,  "#661100"  ,   "gray",  "#dddddd"))+
                scale_x_discrete(limits = c("No diagnoses", 
                                            "Atopic dermatitis", 
                                            "Asthma", "Food allergy", 
                                            "Allergic rhinitis", "One or more diagnoses", "Two or more diagnoses")) + ylim(0.6,4.5)  + theme(legend.position = "none")+
  geom_boxplot(outlier.size=1)
```


```{r}
set.seed(1)
sampledata2 <- as.matrix(ME_1y_species_pruned@sam_data)
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2$SampleID)
sampledata2test <- subset(sampledata2, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$at_least_1_focus_5year_annotated, data=PredictedAgetest)
#W = 29171, p-value = 0.02457
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_1_focus_5year_annotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAge$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
at_least_1_focus_5year_annotated_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
at_least_1_focus_5year_annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_2_5Y != 'NA')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$at_least_2_5Y, data=PredictedAgetest)
#W = 21565, p-value = 0.3984
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$at_least_2_5Y == "1")
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
at_least_2_5Y_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
at_least_2_5Y_age_5year_annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$ad5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$ad5yannotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$ad5yannotated, data=PredictedAgetest)
#W = 19452, p-value = 0.02905
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$ad5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
ad5yannotated_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
ad5yannotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$asthma5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$asthma5yannotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$asthma5yannotated, data=PredictedAgetest)
#W = 19452, p-value = 0.4976
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$asthma5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
asthma5yannotated_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
asthma5yannotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$fa5yannotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$fa5yannotated != '0')
PredictedAgetest1 <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest1$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest1$SampleID)
PredictedAgetest1 <- PredictedAgetest1[reorder_idx, ]
wilcox.test(PredictedAgetest1$PredictedAge~sampledata2test$fa5yannotated, data=PredictedAgetest1)
#W = 5957, p-value = 0.01314
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$fa5yannotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
fa5yannotated_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
fa5yannotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated != 'NA')
sampledata2test <- subset(sampledata2test, sampledata2test$chcla5yq42annotated != '0')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
wilcox.test(PredictedAgetest$PredictedAge~sampledata2test$chcla5yq42annotated, data=PredictedAgetest)
#W = 9229, p-value = 0.1119
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated == '1')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
chcla5yq42annotated_age <- PredictedAgetest$PredictedAge
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
chcla5yq42annotated_age_chronological <- sampledata2test$exact_age

PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
sampledata2test <- subset(sampledata2, sampledata2$chcla5yq42annotated == 'Healthy')
PredictedAgetest <- subset(PredictedAge, SampleID%in%sampledata2test$SampleID)
sampledata2test <- subset(sampledata2test, SampleID%in%PredictedAgetest$SampleID)
reorder_idx <- match(sampledata2test$SampleID,PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
sampledata2test$exact_age <- as.numeric(sampledata2test$exact_age)
healthy_age <- PredictedAgetest$PredictedAge
healthy_age_chronological <- sampledata2test$exact_age

mean(chcla5yq42annotated_age) #0.9204732
mean(fa5yannotated_age) #0.8817454
mean(asthma5yannotated_age) #0.9186628
mean(ad5yannotated_age) #0.902011
mean(at_least_2_5Y_age) #0.917409
mean(at_least_1_focus_5year_annotated_age) #0.9109491
mean(healthy_age) #0.9404741

ggplot()  + theme_classic() + 
  geom_boxplot(aes(x="Atopic dermatitis", y=(ad5yannotated_age * 12)/(ad5yannotated_age_chronological*12), fill = "Atopic dermatitis")) + 
  geom_boxplot(aes(x= "Asthma", y=(asthma5yannotated_age* 12)/(asthma5yannotated_age_chronological*12), fill = "Asthma"))+ 
  geom_boxplot(aes(x="Food allergy", y=(fa5yannotated_age* 12)/(fa5yannotated_age_chronological*12), fill = "Food allergy")) + 
  geom_boxplot(aes(x= "Allergic rhinitis", y=(chcla5yq42annotated_age* 12)/(chcla5yq42annotated_age_chronological*12), fill = "Allergic rhinitis"))+ 
  geom_boxplot(aes(x= "No diagnoses", y=(healthy_age* 12)/(healthy_age_chronological*12), fill = "No diagnoses"))+ 
  geom_boxplot(aes(x="One or more diagnoses", y=(at_least_2_5Y_age* 12)/(at_least_2_5Y_age_5year_annotated_age_chronological*12), fill = "One or more diagnoses")) + 
  geom_boxplot(aes(x= "Two or more diagnoses", y=(at_least_1_focus_5year_annotated_age*12)/(at_least_1_focus_5year_annotated_age_chronological*12), fill = "Two or more diagnoses")) +
  theme(axis.title.x=element_text(size=14, colour = 'black')) +
  theme(axis.title.y=element_text(size=14, colour = 'black')) +
  theme(axis.text.x=element_text(size=14, colour = 'black', angle = 70, hjust = 1)) +
  theme(axis.text.y=element_text(size=14, colour = 'black')) +
  ggtitle("") + 
  ylab("Fungal-derived/chronological age (months)") + 
  xlab("")+
  scale_fill_manual(values = c(
    "#ddcc77" ,   "lavender" ,  "#AA4499" ,   "#117733"   , "#88CCEE" ,  "#661100"  ,   "gray",  "#dddddd"))+
                scale_x_discrete(limits = c("No diagnoses", 
                                            "Atopic dermatitis", 
                                            "Asthma", "Food allergy", 
                                            "Allergic rhinitis", "One or more diagnoses", "Two or more diagnoses")) + ylim(0.3,1.3)  + theme(legend.position = "none")+
  geom_boxplot(outlier.size=1)
```


```{r}

dat <- as.data.frame(ITS2_noUnk_4k_genus_dmm@otu_table)
count <-as.matrix(t(dat))
count[1:5, 1:3]
set.seed(1)
fit <- mclapply(1:10, dmn, count=count, verbose=TRUE)
fit[[4]]
lplc <- sapply(fit, laplace)
plot(lplc, type="b", xlab="Number of Dirichlet Components",
     ylab="Model Fit")
(best <- fit[[which.min(lplc)]])

group <- as.data.frame(best@group)
colnames(group) <- c('Cluster_1', 'Cluster_2', 'Cluster_3', 'Cluster_4')
group$Cluster_1 <- as.numeric(group$Cluster_1)
group$Cluster_2 <- as.numeric(group$Cluster_2)
group$Cluster_3 <- as.numeric(group$Cluster_3)
group$Cluster_4 <- as.numeric(group$Cluster_4)
group$Clusters[group$Cluster_1 > group$Cluster_2 & group$Cluster_1 > group$Cluster_3 & group$Cluster_1 > group$Cluster_4] <- 1
group$Clusters[group$Cluster_3 > group$Cluster_1 & group$Cluster_3 > group$Cluster_2 & group$Cluster_3 > group$Cluster_4] <- 3
group$Clusters[group$Cluster_2 > group$Cluster_1 & group$Cluster_2 > group$Cluster_3 & group$Cluster_2 > group$Cluster_4] <- 2
group$Clusters[group$Cluster_4 > group$Cluster_1 & group$Cluster_4 > group$Cluster_3 & group$Cluster_4 > group$Cluster_2] <- 4

sampledata2 <- as.data.frame(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- subset(sampledata2, rownames(sampledata2)%in%rownames(group))
group <- subset(group, rownames(group)%in%rownames(sampledata2))
reorder_idx <- match(rownames(sampledata2), rownames(group))
group <- group[reorder_idx,  ]
ITS2_noUnk_4k_genus <- subset_samples(ITS2_noUnk_4k_genus, rownames(ITS2_noUnk_4k_genus@sam_data)%in%rownames(group))
ITS2_noUnk_4k_genus@sam_data$Clusters_dmm <- as.factor(group$Clusters)

count <- as.data.frame(ITS2_noUnk_4k_genus_dmm@otu_table)
count <- count + 1
count <- as.matrix(count)
count <- make_relative(count)
count <- log(count)

p0 <- fitted(fit[[1]], scale=TRUE)     # scale by theta
p4 <- fitted(best, scale=TRUE)
colnames(p4) <- paste("m", 1:4, sep="")
(meandiff <- colSums(abs(p4 - as.vector(p0))))
sum(meandiff)

diff <- rowSums(abs(p4 - as.vector(p0)))
o <- order(diff, decreasing=TRUE)
cdiff <- cumsum(diff[o]) / sum(diff)
data <- head(cbind(Mean=p0[o], p4[o,], diff=diff[o], cdiff), 30)
count <- subset(count, rownames(count)%in%rownames(data))

df <- as.data.frame(ITS2_noUnk_4k_genus_dmm@tax_table)
df <- subset(df, rownames(df)%in%rownames(count))
count <- subset(count, rownames(count)%in%rownames(df))
reorder_idx <- match(rownames(count),rownames(df))
df <- df[reorder_idx, ]
count <- as.data.frame(count)
df$Genus[rownames(df) == '4b79a63c290e13054230ad3d5a884aab'] <- 'p__Ascomycota unknown'
df$Genus[rownames(df) == 'c91abf2712996b5c162bd740bf000038'] <- 'k__Fungi unknown'
rownames(count) <- df$Genus

colSide <- brewer.pal(4, "Set1")[ITS2_noUnk_4k_genus_dmm@sam_data$Clusters_dmm]
Heatmap(t(count), name = "mtcars", split = ITS2_noUnk_4k_genus_dmm@sam_data$Clusters_dmm)
```


```{r}
data_3mo <- subset(as.data.frame(ITS2_noUnk_4k_genus@sam_data), Visit == '3 month')
data_1y <- subset(as.data.frame(ITS2_noUnk_4k_genus@sam_data), Visit == '1 year')
data_3mo <- subset(data_3mo, data_3mo$SubjectNumber%in%data_1y$SubjectNumber)
data_1y <- subset(data_1y, data_1y$SubjectNumber%in%data_3mo$SubjectNumber)
reorder_idx <- match(data_1y$SubjectNumber, data_3mo$SubjectNumber)
data_3mo <- data_3mo[reorder_idx,  ]
data_3mo$Clusters_3mo <- data_3mo$Clusters_dmm
data_1y$Clusters_1y <- data_1y$Clusters_dmm
data_1y$Clusters_3mo <- data_3mo$Clusters_3mo
nrow(subset(data_1y, Clusters_3mo == 1 & Clusters_1y ==1))
nrow(subset(data_1y, Clusters_3mo == 1 & Clusters_1y == 2))
nrow(subset(data_1y, Clusters_3mo == 1 & Clusters_1y == 3))
nrow(subset(data_1y, Clusters_3mo == 1 & Clusters_1y == 4))
nrow(subset(data_1y, Clusters_3mo == 2 & Clusters_1y ==1))
nrow(subset(data_1y, Clusters_3mo == 2 & Clusters_1y == 2))
nrow(subset(data_1y, Clusters_3mo == 2 & Clusters_1y == 3))
nrow(subset(data_1y, Clusters_3mo == 2 & Clusters_1y == 4))
nrow(subset(data_1y, Clusters_3mo == 3 & Clusters_1y ==1))
#nrow(subset(data_1y, Clusters_3mo == 3 & Clusters_1y == 2)) == 0
nrow(subset(data_1y, Clusters_3mo == 3 & Clusters_1y == 3))
nrow(subset(data_1y, Clusters_3mo == 3 & Clusters_1y == 4))
nrow(subset(data_1y, Clusters_3mo == 4 & Clusters_1y ==1))
nrow(subset(data_1y, Clusters_3mo == 4 & Clusters_1y == 2))
nrow(subset(data_1y, Clusters_3mo == 4 & Clusters_1y == 3))
nrow(subset(data_1y, Clusters_3mo == 4 & Clusters_1y == 4))

links <- data.frame(source=c("Cluster 1 at 3mo","Cluster 1 at 3mo", "Cluster 1 at 3mo", "Cluster 1 at 3mo", "Cluster 2 at 3mo","Cluster 2 at 3mo", "Cluster 2 at 3mo", "Cluster 2 at 3mo", "Cluster 3 at 3mo", "Cluster 3 at 3mo","Cluster 3 at 3mo", "Cluster 3 at 3mo",  "Cluster 4 at 3mo", "Cluster 4 at 3mo", "Cluster 4 at 3mo","Cluster 4 at 3mo"), target=c("Cluster 1 at 1y","Cluster 2 at 1y", "Cluster 3 at 1y", "Cluster 4 at 1y", "Cluster 1 at 1y","Cluster 2 at 1y", "Cluster 3 at 1y", "Cluster 4 at 1y",  "Cluster 1 at 1y", "Cluster 2 at 1y","Cluster 3 at 1y", "Cluster 4 at 1y", "Cluster 1 at 1y", "Cluster 2 at 1y", "Cluster 3 at 1y","Cluster 4 at 1y"), value=c(57, 13, 145, 121, 68, 30, 170, 148, 3, 0, 5, 8, 13, 4, 24, 24) )
nodes <- data.frame(
name=c(as.character(links$source),
as.character(links$target)) %>% unique()
)
links$IDsource <- match(links$source, nodes$name)-1
links$IDtarget <- match(links$target, nodes$name)-1
p <- sankeyNetwork(Links = links, Nodes = nodes,
Source = "IDsource", Target = "IDtarget",
Value = "value", NodeID = "name",
sinksRight=FALSE)
p
```


```{r}
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
data_1y <- subset(as.data.frame(ITS2_noUnk_4k_genus@sam_data), Visit == '1 year')
PredictedAge <- subset(PredictedAge, rownames(PredictedAge)%in%rownames(data_1y))
data_1y <- subset(data_1y, rownames(data_1y)%in%rownames(PredictedAge))
reorder_idx <- match(rownames(PredictedAge),rownames(data_1y))
data_1y <- data_1y[reorder_idx, ]
data_1y$Predictedage <- as.numeric(PredictedAge$PredictAge)
data_1y$Clusters_dmm_12v34 <- 'NA'
data_1y$Clusters_dmm_12v34[data_1y$Clusters_dmm == 3 | data_1y$Clusters_dmm ==4] <- 'Late'
data_1y$Clusters_dmm_12v34[data_1y$Clusters_dmm == 1 | data_1y$Clusters_dmm ==2] <- 'Early'
wilcox.test(data_1y$agedays~data_1y$Clusters_dmm_12v34)
wilcox.test(data_1y$Predictedage~data_1y$Clusters_dmm_12v34)

ggplot(data_1y, aes(x=data_1y$Clusters_dmm_12v34, y=data_1y$agedays/30, fill = data_1y$Clusters_dmm_12v34))  + theme_classic() +
    geom_boxplot() +
    theme(axis.title.x=element_text(size=14, colour = 'black')) +
    theme(axis.title.y=element_text(size=14, colour = 'black')) +
    theme(axis.text.x=element_text(size=14, colour = 'black')) +
    theme(axis.text.y=element_text(size=14, colour = 'black')) +
    ggtitle("") +
    ylab("Chronological age (months)") +
    xlab("")+ theme(legend.position = "none")+
    geom_boxplot(outlier.size=0.5) + xlab("Clusters")

ggplot(data_1y, aes(x=data_1y$Clusters_dmm_12v34, y=data_1y$Predictedage*12, fill = data_1y$Clusters_dmm_12v34))  + theme_classic() +
    geom_boxplot() +
    theme(axis.title.x=element_text(size=14, colour = 'black')) +
    theme(axis.title.y=element_text(size=14, colour = 'black')) +
    theme(axis.text.x=element_text(size=14, colour = 'black')) +
    theme(axis.text.y=element_text(size=14, colour = 'black')) +
    ggtitle("") +
    ylab("Predicted age (months)") +
    xlab("")+ theme(legend.position = "none")+
    geom_boxplot(outlier.size=0.5) + xlab("Clusters")

data_1y$ad5y[data_1y$ad5y == "Possible AD"] <- NA
fisher.test(data_1y$Clusters_dmm_12v34, y = data_1y$ad5y, alternative = "two.sided",
conf.int = TRUE, conf.level = 0.95,
simulate.p.value = FALSE, B = 2000)

dat <- data.frame(
"AD_no" = c(214, 726),"AD_yes" = c(63, 122),
row.names = c("Clusters 1 or 2", "Clusters 3 or 4"),
stringsAsFactors = FALSE
)
colnames(dat) <- c("No AD at 5Y", "AD at 5Y")
mosaicplot(dat,
main = "Mosaic plot",
color = TRUE
)
```


```{r}

sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%rownames(sampledata2))
sampledata2test <- subset(sampledata2, rownames(sampledata2)%in%PredictedAgetest$SampleID)
reorder_idx <- match(rownames(sampledata2test),PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
sampledata2test$PredictedAge <- as.numeric(PredictedAgetest$PredictedAge)
data_1y <- subset(sampledata2test, Visit == '1 year')
data_1y$Clusters_1y <- data_1y$Clusters_dmm_binary

BatchCorrect_NMR_LCMS_combinedmatrix <- read_csv("~/Desktop/BatchCorrect_NMR_LCMS_combinedmatrix.csv")
BatchCorrect_NMR_LCMS_combinedmatrix <- as.data.frame(BatchCorrect_NMR_LCMS_combinedmatrix)
rownames(BatchCorrect_NMR_LCMS_combinedmatrix) <- BatchCorrect_NMR_LCMS_combinedmatrix$...1
BatchCorrect_NMR_LCMS_combinedmatrix <- BatchCorrect_NMR_LCMS_combinedmatrix[, !(colnames(BatchCorrect_NMR_LCMS_combinedmatrix) %in% c("...1"))]
BatchCorrect_NMR_LCMS_combinedmatrix <- subset(BatchCorrect_NMR_LCMS_combinedmatrix, rownames(BatchCorrect_NMR_LCMS_combinedmatrix)%in%rownames(data_1y))
data_1y <- subset(data_1y, 
                      rownames(data_1y)%in%rownames(BatchCorrect_NMR_LCMS_combinedmatrix))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(rownames(data_1y),rownames(BatchCorrect_NMR_LCMS_combinedmatrix))
BatchCorrect_NMR_LCMS_combinedmatrix <- BatchCorrect_NMR_LCMS_combinedmatrix[reorder_idx, ]
data_1y$agedays <- as.numeric(data_1y$agedays)

Child_Stool_1Y <- read.csv('Child_Stool_1_year.csv')
Child_Stool_1Y$BarCode <- gsub('\\-', '.', Child_Stool_1Y$BarCode)
Child_Stool_1Y$BarCode <- substr(Child_Stool_1Y$BarCode, 1, nchar(Child_Stool_1Y$BarCode)-4)
data_1y$SampleID <- substr(data_1y$SampleID, 1, nchar(data_1y$SampleID)-4)
Child_Stool_1Y <- subset(Child_Stool_1Y, Child_Stool_1Y$BarCode%in%data_1y$SampleID)
rownames(Child_Stool_1Y) <- Child_Stool_1Y$BarCode
data_1y <- subset(data_1y, 
                      data_1y$SampleID%in%rownames(Child_Stool_1Y))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(data_1y$SampleID,rownames(Child_Stool_1Y))
Child_Stool_1Y <- Child_Stool_1Y[reorder_idx, ]
data_1y$ProcessingPeriod <- as.numeric(Child_Stool_1Y$ProcessingPeriod)

fit_data = Maaslin2(
  input_data = BatchCorrect_NMR_LCMS_combinedmatrix, 
  input_metadata = data_1y, 
  output = "output", 
  fixed_effects = c('PredictedAge', 'agedays', 'ProcessingPeriod'),
  random_effects = c( 'site' ),
  reference = c('site,vancouver'), 
  normalization = 'NONE', transform = 'NONE')

fit_data_df_predictedage <- as.data.frame(fit_data$results)
fit_data_df_predictedage <- subset(fit_data_df_predictedage, metadata == "PredictedAge")

#species

sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%rownames(sampledata2))
sampledata2test <- subset(sampledata2, rownames(sampledata2)%in%PredictedAgetest$SampleID)
reorder_idx <- match(rownames(sampledata2test),PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
sampledata2test$PredictedAge <- as.numeric(PredictedAgetest$PredictedAge)
data_1y <- subset(sampledata2test, Visit == '1 year')
data_1y$Clusters_1y <- data_1y$Clusters_dmm_binary

RBNME_species_prev <- aggregate_rare(RBNME_species, level = "SpeciesSGB", detection = 0/100, prevalence = 10/100)
RBNME_species_prev <- subset_taxa(RBNME_species_prev, SpeciesSGB != 'Other')
RBNME_species_prev_1y <- subset_samples(RBNME_species_prev, Visit == '1 year')
otu <- as.matrix(RBNME_species_prev_1y@otu_table)
otu <- as.data.frame(t(otu))
data_1y <- subset(data_1y, 
                      rownames(data_1y)%in%rownames(otu))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(rownames(data_1y),rownames(otu))
otu <- otu[reorder_idx, ]
data_1y$agedays <- as.numeric(data_1y$agedays)

Child_Stool_1Y <- read.csv('Child_Stool_1_year.csv')
Child_Stool_1Y$BarCode <- gsub('\\-', '.', Child_Stool_1Y$BarCode)
Child_Stool_1Y$BarCode <- substr(Child_Stool_1Y$BarCode, 1, nchar(Child_Stool_1Y$BarCode)-4)
data_1y$SampleID <- substr(data_1y$SampleID, 1, nchar(data_1y$SampleID)-4)
Child_Stool_1Y <- subset(Child_Stool_1Y, Child_Stool_1Y$BarCode%in%data_1y$SampleID)
rownames(Child_Stool_1Y) <- Child_Stool_1Y$BarCode
data_1y <- subset(data_1y, 
                      data_1y$SampleID%in%rownames(Child_Stool_1Y))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(data_1y$SampleID,rownames(Child_Stool_1Y))
Child_Stool_1Y <- Child_Stool_1Y[reorder_idx, ]
data_1y$ProcessingPeriod <- as.numeric(Child_Stool_1Y$ProcessingPeriod)

fit_data = Maaslin2(
  input_data = otu, 
  input_metadata = data_1y, 
  output = "output", 
  fixed_effects = c('PredictedAge', 'agedays', 'ProcessingPeriod'),
  random_effects = c( 'site' ),
  reference = c('site,vancouver'), 
  normalization = 'NONE', transform = 'NONE')

fit_data_df_predictedage_otu <- as.data.frame(fit_data$results)
fit_data_df_predictedage_otu <- subset(fit_data_df_predictedage_otu, metadata == "PredictedAge")
fit_data_df_predictedage_otu <- subset(fit_data_df_predictedage_otu, qval<0.1)


#pathways 

sampledata2 <- as.matrix(ITS2_noUnk_4k_genus@sam_data)
sampledata2 <- as.data.frame(sampledata2)
PredictedAge <- as.data.frame(PREDAGE[["RB_ITS"]][["PredictedAge"]])
colnames(PredictedAge) <- 'PredictedAge'
PredictedAge$SampleID <- rownames(PredictedAge)
PredictedAgetest <- subset(PredictedAge, SampleID%in%rownames(sampledata2))
sampledata2test <- subset(sampledata2, rownames(sampledata2)%in%PredictedAgetest$SampleID)
reorder_idx <- match(rownames(sampledata2test),PredictedAgetest$SampleID)
PredictedAgetest <- PredictedAgetest[reorder_idx, ]
sampledata2test$PredictedAge <- as.numeric(PredictedAgetest$PredictedAge)
data_1y <- subset(sampledata2test, Visit == '1 year')
data_1y$Clusters_1y <- data_1y$Clusters_dmm_binary

RBMETA_prev <- aggregate_rare(RBMETA, level = "X..Pathway", detection = 0/100, prevalence = 10/100)
RBMETA_prev <- subset_taxa(RBMETA_prev, X..Pathway != 'Other')
RBMETA_prev_1y <- subset_samples(RBMETA_prev, Visit == '1 year')
otu <- as.matrix(RBMETA_prev_1y@otu_table)
otu <- as.data.frame(t(otu))
otu <- otu[, !(colnames(otu) %in% c("REDCITCYC: TCA cycle VI (Helicobacter)"))]
data_1y <- subset(data_1y, 
                      rownames(data_1y)%in%rownames(otu))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(rownames(data_1y),rownames(otu))
otu <- otu[reorder_idx, ]
data_1y$agedays <- as.numeric(data_1y$agedays)

Child_Stool_1Y <- read.csv('Child_Stool_1_year.csv')
Child_Stool_1Y$BarCode <- gsub('\\-', '.', Child_Stool_1Y$BarCode)
Child_Stool_1Y$BarCode <- substr(Child_Stool_1Y$BarCode, 1, nchar(Child_Stool_1Y$BarCode)-4)
data_1y$SampleID <- substr(data_1y$SampleID, 1, nchar(data_1y$SampleID)-4)
Child_Stool_1Y <- subset(Child_Stool_1Y, Child_Stool_1Y$BarCode%in%data_1y$SampleID)
rownames(Child_Stool_1Y) <- Child_Stool_1Y$BarCode
data_1y <- subset(data_1y, 
                      data_1y$SampleID%in%rownames(Child_Stool_1Y))
data_1y <- as.data.frame(data_1y)
reorder_idx <- match(data_1y$SampleID,rownames(Child_Stool_1Y))
Child_Stool_1Y <- Child_Stool_1Y[reorder_idx, ]
data_1y$ProcessingPeriod <- as.numeric(Child_Stool_1Y$ProcessingPeriod)

fit_data = Maaslin2(
  input_data = otu, 
  input_metadata = data_1y, 
  output = "output", 
  fixed_effects = c('PredictedAge', 'agedays', 'ProcessingPeriod'),
  random_effects = c( 'site' ),
  reference = c('site,vancouver'), 
  normalization = 'NONE', transform = 'NONE')

fit_data_df_predictedage_pathways <- as.data.frame(fit_data$results)
fit_data_df_predictedage_pathways <- subset(fit_data_df_predictedage_pathways, metadata == "PredictedAge")
fit_data_df_predictedage_pathways <- subset(fit_data_df_predictedage_pathways, qval<0.1)

```

